DATASETS:
  TRAIN: ("voc_ablation_train",)
  TEST: ("voc_ablation_val",)

MODEL:
  SAN:
    NUM_CLASSES: 20           # VOC 20类
    CLIP_MODEL_NAME: "ViT-B/16"
    CLIP_PRETRAINED_NAME: "openai"
    CLIP_TEMPLATE_SET: "vild"
    FEATURE_LAST_LAYER_IDX: 9

  SIDE_ADAPTER:
    VIT_NAME: "vit_w240n6d8_patch16"
    PRETRAINED: false
    IMAGE_SIZE: 640
    DROP_PATH_RATE: 0.0
    NUM_QUERIES: 100
    FUSION_TYPE: "add"
    DEEP_SUPERVISION_IDXS: [7, 8]
    ATTN_BIAS:
      NUM_HEADS: 12
      NUM_LAYERS: 1
      EMBED_CHANNELS: 256
      MLP_CHANNELS: 256
      MLP_NUM_LAYERS: 3
      RESCALE_ATTN_BIAS: true

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  MAX_ITER: 20000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 500
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_MULTIPLIER: 1.0
  TEST_IMS_PER_BATCH: 1
  CLIP_GRADIENTS:
    ENABLED: true
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: true
  CHECKPOINT_PERIOD: 20000

INPUT:
  MIN_SIZE_TRAIN: [320, 384, 448, 512, 576, 640]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 640
  MAX_SIZE_TRAIN: 2560
  MAX_SIZE_TEST: 2560
  CROP:
    ENABLED: true
    TYPE: "absolute"
    SIZE: [640, 640]
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: true
  SIZE_DIVISIBILITY: 640
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_semantic"

TEST:
  EVAL_PERIOD: 2000
  AUG:
    ENABLED: false

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: true
  NUM_WORKERS: 4

VERSION: 2

WANDB:
  PROJECT: "san_ablation"
  NAME: null
